name: DotNetEvetyDay.Extensions - Nuget publishing

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: DotNet setup
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
      working-directory: src
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
      working-directory: src
    - name: Pack
      run: dotnet pack --configuration Release --no-build --output .
      working-directory: src/DotNetEveryDay.Extensions
    - name: Push
      run: dotnet nuget push DotNetEveryDay.Extensions.${VERSION}.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN}
      working-directory: src/DotNetEveryDay.Extensions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}